const fs = require('fs');
const os = require('os');
const path = require('path');
const { BoxClient, BoxOAuth, OAuthConfig, BoxDeveloperTokenAuth } = require('box-node-sdk/sdk-gen');

// Kept in the user's profile, outside the project, so it can't end up
// committed, deployed, or synced into a shared folder by mistake.
const DIR = path.join(os.homedir(), '.box-migration');
const APP_FILE = path.join(DIR, 'app.json');
const TOKEN_FILE = path.join(DIR, 'tokens.json');
const REDIRECT_URI = 'http://localhost:8765/callback';

function ensureDir() {
  fs.mkdirSync(DIR, { recursive: true });
}

// Box rotates the refresh token every time it's used, so every new token
// pair must be written back, or the login stops working after the first
// refresh.
class FileTokenStorage {
  async store(token) {
    ensureDir();
    fs.writeFileSync(
      TOKEN_FILE,
      JSON.stringify({
        accessToken: token.accessToken,
        refreshToken: token.refreshToken,
        expiresIn: token.expiresIn,
        tokenType: token.tokenType,
        savedAt: new Date().toISOString(),
      }),
      { mode: 0o600 }
    );
    return undefined;
  }

  async get() {
    if (!fs.existsSync(TOKEN_FILE)) return undefined;
    return JSON.parse(fs.readFileSync(TOKEN_FILE, 'utf8'));
  }

  async clear() {
    if (fs.existsSync(TOKEN_FILE)) fs.unlinkSync(TOKEN_FILE);
    return undefined;
  }
}

function readAppConfig() {
  if (!fs.existsSync(APP_FILE)) return null;
  return JSON.parse(fs.readFileSync(APP_FILE, 'utf8'));
}

function saveAppConfig(clientId, clientSecret) {
  ensureDir();
  fs.writeFileSync(APP_FILE, JSON.stringify({ clientId, clientSecret }), { mode: 0o600 });
}

function buildAuth(clientId, clientSecret) {
  return new BoxOAuth({
    config: new OAuthConfig({ clientId, clientSecret, tokenStorage: new FileTokenStorage() }),
  });
}

function hasStoredLogin() {
  return fs.existsSync(APP_FILE) && fs.existsSync(TOKEN_FILE);
}

/** A Box client that acts as whoever signed in with tools/boxLogin.js. */
function getBoxClientFromStoredLogin() {
  const app = readAppConfig();
  if (!app || !fs.existsSync(TOKEN_FILE)) {
    throw new Error('No stored login. Run "node tools/boxLogin.js" first and sign in as the folders\' current owner.');
  }
  return new BoxClient({ auth: buildAuth(app.clientId, app.clientSecret) });
}

function clearStoredLogin() {
  for (const f of [TOKEN_FILE, APP_FILE]) if (fs.existsSync(f)) fs.unlinkSync(f);
}

/**
 * A Box client from a short-lived developer token (Developer Console →
 * your app → Configuration → Developer Token). Handy for a quick one-off
 * run without setting up the OAuth login below, but it expires in 60
 * minutes and has to be regenerated by hand each time. The stored login
 * is the better option for anything beyond a single test.
 */
function getBoxClientFromToken(token) {
  return new BoxClient({ auth: new BoxDeveloperTokenAuth({ token }) });
}

module.exports = {
  DIR, REDIRECT_URI, FileTokenStorage, buildAuth, saveAppConfig, readAppConfig,
  hasStoredLogin, getBoxClientFromStoredLogin, clearStoredLogin, getBoxClientFromToken,
};
